### ISSUE TITLE
Scaling with PLASMA_USE_QT_SCALING=1

### ISSUE THREAD

**Issue by gondsman** [psifidotos/applet-window-buttons#157] opened 2021-12-26 11:47 UTC
I have the applet show the buttons only for maximized windows. This works fine normally with any screen scaling by default.
If I try to set PLASMA_USE_QT_SCALING=1 in order to solve a lot of minor scaling issues with Plasma the applet stops being able to recognize if a window is maximized. In fact, if I set it up to show if "active window is present" it only detects the window if it's placed in the top left part of the screen (a quarter of the screen if the scaling factor is 200%). I believe this is an issue with plasma and not with this applet, as the pager has the same issue: https://bugs.kde.org/show_bug.cgi?id=446627

I know this is a long shot and I perfectly understand if it gets closed as WONTFIX, since this configuration is not officially supported and the bug is probably not even in this applet, but I felt like you might want to know of the bug anyway, especially because you already fixed similar issued in latte-dock. Maybe there's another simple way to tell if a window is maximized that works around this issue.
Thanks anyway!

**Comment by psifidotos** [comment] 2021-12-26 13:11
Are you using the applet inside a plasma panel?

**Comment by gondsman** [comment] 2021-12-26 13:13
No, it's in a latte panel. I do have a standard plasma panel, but it's not the one hosting the applet.

**Comment by psifidotos** [comment] 2021-12-26 13:17
What is you Latte version?

**Comment by psifidotos** [comment] 2021-12-26 13:19
https://psifidotos.blogspot.com/2021/10/latte-dock-v0103-bug-fix-release.html it requires 0.10.3 in order for PLASMA_USE_QT_SCALING to work correctly.

**Comment by gondsman** [comment] 2021-12-26 14:17
Latte-dock version: 0.10.6
window-buttons applet version: 0.10.1
Plasma version: 5.23.4

I can attack some screenshots to try to explain better, because the behaviour is even stranger than I initially thought.

The latte panel is set up to get colors from "any touching window", the buttons applet to show if "active window is present".

If the window is in the top left corner (even when not touching the latte panel) the buttons are shown and the panel gets the color from the window:
![latte_scaling_bug_1](https://user-images.githubusercontent.com/45125414/147410714-bf5b32e9-5d69-4f0e-a1d3-09683b0b4193.png)

If I move the window down, the buttons disappear but the latte panel still gets the color from the window:
![latte_scaling_bug_2](https://user-images.githubusercontent.com/45125414/147410790-331102a0-f967-48d8-b038-1f25987c31a5.png)
This case is also the behaviour when the window is maximized.

If I move the window further down, the panel stops getting the color from it:
![latte_scaling_bug_3](https://user-images.githubusercontent.com/45125414/147410810-7356a4aa-d4a9-45be-982c-3cbc5b911248.png)

I don't know if you need a log or a setting file. This is with a 3840x2400 screen set up with 200% scaling.

**Comment by psifidotos** [comment] 2021-12-26 17:46
My guess is that Latte ignores the window if it is too far down  because the center of the window is out of the screen geometry. Hmmm... probably a latte issue.

Are you in multi-screen environment?

**Comment by gondsman** [comment] 2021-12-26 18:03
This is with a single screen.

By the way, even the second screen is wrong because the panel should be colored only if the window is touching it, shouldn't it?

**Comment by gondsman** [comment] 2021-12-26 18:05
Also I should add that without the PLASMA_USE_QT_SCALING=1 everything works exactly as expected, both for the buttons and for the panel color.

**Comment by psifidotos** [comment] 2021-12-27 16:08
@gondsman the issue you have discovered is really important and points to Latte.

1. For you coloring my guess is that at Latte Behavior advanced settings you have chosen Colors->From Window->Current Active Window, you can adjust it to From Window-> Any Touching Window
2. The fact when moving the window center under the screen geometry creates this issue is really important... I think the best approach to fix this in Latte is to check the entire window geometry if intersects with the screen geometry...

**Comment by psifidotos** [comment] 2021-12-27 21:32
should be fixed in upcoming Latte v0.10.7
https://invent.kde.org/plasma/latte-dock/-/commit/abcacface8a2bc82c02a14910f0ddcb97354d326

**Comment by gondsman** [comment] 2021-12-28 15:42
> 1. For you coloring my guess is that at Latte Behavior advanced settings you have chosen Colors->From Window->Current Active Window, you can adjust it to From Window-> Any Touching Window

It is already set to "any touching window". in fact I don't see any difference between the two options (again, this works fine without the PLASMA_USE_QT_SCALING variable).

**Comment by psifidotos** [comment] 2021-12-28 15:56
For the main issue you should wait 0.10.7

For the coloring issue you should report to Latte bug tracker with proper information and steps to reproduce. 
https://bugs.kde.org/enter_bug.cgi?product=lattedock

**Closed by psifidotos** 2021-12-28 15:56 UTC

**Comment by psifidotos** [comment] 2021-12-28 16:04
And add up on the discussion, are you using x11 or wayland?

**Comment by gondsman** [comment] 2021-12-28 16:08
This is on X11, on an intel iGPU.

**Comment by gondsman** [comment] 2022-01-21 08:33
I updated to latte 10.7 but the issue is still not solved. Now the position for which it works is bigger as the window just needs to intersect with the top-right quarter of the screen rather than its center be there, but the underlying issue is still there.
On the other hand, I've just read that the PLASMA_USE_QT_SCALING effort was given up on (https://bugs.kde.org/show_bug.cgi?id=356446),  so I don't even know if it's worth investigating this more.
