### ISSUE TITLE
 Doesn't show on my widget list after installing it

### ISSUE THREAD

**Issue by Zardoz89** [psifidotos/applet-window-buttons#19] opened 2018-11-14 08:01 UTC
Doesn't show on my widget list after installing it. I'm using:

Operating System: Kubuntu 18.04
KDE Plasma Version: 5.44.0
Qt Version: 5.9.5

**Comment by psifidotos** [comment] 2018-11-14 15:53
Duplicate of #20

**Closed by psifidotos** 2018-11-14 15:53 UTC
